"""Static first-pass workflow map metadata for the UI How To page."""

from __future__ import annotations

from typing import Any


WORKFLOW_PHASES: list[dict[str, str]] = [
    {"key": "configs", "title": "Config Inputs"},
    {"key": "performance", "title": "Performance And Analysis"},
    {"key": "geometry", "title": "Geometry And Flow Physics"},
    {"key": "hardware", "title": "Hardware Sizing"},
    {"key": "verification", "title": "Verification And Campaigns"},
]


WORKFLOW_NODES: list[dict[str, Any]] = [
    {
        "id": "design_config",
        "title": "Design Config",
        "kind": "config",
        "phase": "configs",
        "description": "Primary study definition for nominal performance, geometry, internal ballistics, and downstream hardware sizing.",
        "inputs": [],
        "outputs": ["study_config in memory"],
    },
    {
        "id": "cea_config",
        "title": "CEA Config",
        "kind": "config",
        "phase": "configs",
        "description": "Thermochemistry sweep settings, reactant setup, and area-ratio search controls.",
        "inputs": [],
        "outputs": ["raw CEA sweep configuration"],
    },
    {
        "id": "hydraulic_config",
        "title": "Hydraulic Config",
        "kind": "config",
        "phase": "configs",
        "description": "Rig dataset locations, calibration settings, and hydraulic comparison options.",
        "inputs": [],
        "outputs": ["hydraulic validation settings"],
    },
    {
        "id": "structural_config",
        "title": "Structural Config",
        "kind": "config",
        "phase": "configs",
        "description": "Structural materials, load-source policy, closure sizing rules, and thickness limits.",
        "inputs": [],
        "outputs": ["structural sizing settings"],
    },
    {
        "id": "thermal_config",
        "title": "Thermal Config",
        "kind": "config",
        "phase": "configs",
        "description": "Thermal load cases, allowable temperatures, and wall-model assumptions.",
        "inputs": [],
        "outputs": ["thermal sizing settings"],
    },
    {
        "id": "nozzle_config",
        "title": "Nozzle Off-Design Config",
        "kind": "config",
        "phase": "configs",
        "description": "Ambient environments, off-design checks, and recommendation thresholds.",
        "inputs": [],
        "outputs": ["nozzle off-design settings"],
    },
    {
        "id": "cfd_config",
        "title": "CFD Config",
        "kind": "config",
        "phase": "configs",
        "description": "CFD campaign targets, case-export settings, and correction-ingest options.",
        "inputs": [],
        "outputs": ["CFD workflow settings"],
    },
    {
        "id": "testing_config",
        "title": "Testing Config",
        "kind": "config",
        "phase": "configs",
        "description": "Campaign staging, dataset ingest rules, model-vs-test options, and readiness gates.",
        "inputs": [],
        "outputs": ["testing workflow settings"],
    },
    {
        "id": "cea",
        "title": "Thermochemistry",
        "kind": "workflow",
        "phase": "performance",
        "description": "Runs NASA CEA sweeps and writes the highest-Isp reference case.",
        "inputs": ["CEA config"],
        "outputs": ["thermochemistry/all_cases.csv", "thermochemistry/highest_isp_case.json", "thermochemistry sweep plots"],
    },
    {
        "id": "nominal",
        "title": "Nominal Performance",
        "kind": "workflow",
        "phase": "performance",
        "description": "Runs the reduced-order 0D nominal case and produces the shared transient history used by many later steps.",
        "inputs": ["Design config", "optional frozen geometry", "optional injector geometry", "optional CEA raw config"],
        "outputs": ["performance/nominal_history.csv", "performance/nominal_metrics.json", "performance SVG plots"],
    },
    {
        "id": "oat",
        "title": "Sensitivity",
        "kind": "workflow",
        "phase": "performance",
        "description": "One-at-a-time perturbation study used to identify dominant design drivers.",
        "inputs": ["Design config"],
        "outputs": ["analysis/sensitivity/oat_cases.csv", "analysis/sensitivity ranking SVGs"],
    },
    {
        "id": "corners",
        "title": "Corner Cases",
        "kind": "workflow",
        "phase": "performance",
        "description": "Evaluates named hot, cold, and risk corners to create envelopes for geometry and hardware checks.",
        "inputs": ["Design config"],
        "outputs": ["analysis/corners/corner_case_summary.csv", "corner overlay SVGs"],
    },
    {
        "id": "geometry",
        "title": "Geometry Freeze",
        "kind": "workflow",
        "phase": "geometry",
        "description": "Freezes the baseline chamber, grain, injector-face, throat, and nozzle geometry and records context used downstream.",
        "inputs": ["Design config", "CEA reference case", "nominal metrics", "optional sensitivity rankings", "optional corner envelopes"],
        "outputs": ["geometry/geometry_definition.json", "geometry/geometry_definition.csv", "geometry/geometry_summary.txt"],
    },
    {
        "id": "internal_ballistics",
        "title": "Internal Ballistics",
        "kind": "workflow",
        "phase": "geometry",
        "description": "Runs the quasi-1D solver with frozen geometry and produces transient ballistic histories.",
        "inputs": ["Design config", "CEA raw config", "geometry_definition.json", "optional injector geometry"],
        "outputs": ["internal_ballistics/*.csv", "internal_ballistics metrics", "internal ballistics plots"],
    },
    {
        "id": "injector_design",
        "title": "Injector Design",
        "kind": "workflow",
        "phase": "geometry",
        "description": "Synthesizes showerhead injector geometry and an effective reduced-order injector model.",
        "inputs": ["Design config", "CEA raw config", "geometry_definition.json"],
        "outputs": ["injector_design/injector_geometry.json", "injector_design effective model", "injector design plots"],
    },
    {
        "id": "hydraulic_predict",
        "title": "Hydraulic Predict",
        "kind": "workflow",
        "phase": "geometry",
        "description": "Compares measured hydraulic rig points against the current nominal feed and injector model.",
        "inputs": ["Design config", "Hydraulic config", "optional injector geometry"],
        "outputs": ["hydraulic_validation prediction statistics", "hydraulic comparison tables"],
    },
    {
        "id": "hydraulic_calibrate",
        "title": "Hydraulic Calibrate",
        "kind": "workflow",
        "phase": "geometry",
        "description": "Fits feed and injector corrections and writes a reusable calibration package.",
        "inputs": ["Design config", "Hydraulic config", "optional injector geometry"],
        "outputs": ["hydraulic_validation calibration package", "calibrated comparison tables"],
    },
    {
        "id": "hydraulic_compare",
        "title": "Hydraulic Compare",
        "kind": "workflow",
        "phase": "geometry",
        "description": "Loads a saved hydraulic calibration package and compares nominal versus corrected predictions.",
        "inputs": ["Design config", "Hydraulic config", "calibration package"],
        "outputs": ["hydraulic_validation calibrated comparison outputs"],
    },
    {
        "id": "structural_size",
        "title": "Structural Sizing",
        "kind": "workflow",
        "phase": "hardware",
        "description": "Sizes chamber shell, closures, injector plate, grain support, and first-pass structural mass.",
        "inputs": ["Design config", "Structural config", "geometry_definition.json", "nominal loads", "optional corner envelopes", "optional internal ballistics", "optional injector geometry"],
        "outputs": ["structural/structural_sizing.json", "structural mass CSVs", "structural SVG plots"],
    },
    {
        "id": "thermal_size",
        "title": "Thermal Sizing",
        "kind": "workflow",
        "phase": "hardware",
        "description": "Checks chamber, throat, nozzle, and injector-face thermal survivability using nominal and optional 1D histories.",
        "inputs": ["Design config", "Structural config", "Thermal config", "geometry_definition.json", "structural_sizing.json", "nominal history", "optional internal ballistics", "optional injector geometry"],
        "outputs": ["thermal/thermal_sizing.json", "thermal_region_histories.csv", "thermal SVG plots"],
    },
    {
        "id": "nozzle_offdesign",
        "title": "Nozzle Off-Design",
        "kind": "workflow",
        "phase": "hardware",
        "description": "Evaluates ambient sensitivity, separation risk, and recommended usage across ground and flight environments.",
        "inputs": ["Design config", "Structural config", "Thermal config", "Nozzle off-design config", "geometry_definition.json", "structural_sizing.json", "thermal_sizing.json", "nominal history", "optional corner envelopes", "optional internal ballistics"],
        "outputs": ["nozzle_offdesign/nozzle_offdesign_results.json", "nozzle_operating_points.csv", "nozzle SVG plots"],
    },
    {
        "id": "cfd_plan",
        "title": "CFD Plan",
        "kind": "workflow",
        "phase": "verification",
        "description": "Builds the ordered CFD campaign, targets, operating points, and correction templates.",
        "inputs": ["Design config", "CFD config", "geometry_definition.json", "injector geometry", "structural_sizing.json", "thermal_sizing.json", "nozzle_offdesign_results.json", "nominal history", "optional corners", "optional internal ballistics"],
        "outputs": ["cfd/cfd_campaign_plan.json", "cfd_targets.csv", "cfd SVG plots"],
    },
    {
        "id": "cfd_export_cases",
        "title": "CFD Export Cases",
        "kind": "workflow",
        "phase": "verification",
        "description": "Exports structured CFD case definitions, geometry packages, and boundary conditions for external solvers.",
        "inputs": ["CFD plan context", "geometry_definition.json", "nominal/corner/1D operating points"],
        "outputs": ["cfd/cases/*", "cfd/cfd_case_definitions.json", "cfd geometry packages"],
    },
    {
        "id": "cfd_ingest_results",
        "title": "CFD Ingest Results",
        "kind": "workflow",
        "phase": "verification",
        "description": "Loads summarized CFD outputs and converts them into reduced-order correction packages.",
        "inputs": ["CFD config", "external CFD summary files", "cfd_case_definitions.json"],
        "outputs": ["cfd correction packages", "cfd result summaries", "updated impact report"],
    },
    {
        "id": "cfd_apply_corrections",
        "title": "CFD Apply Corrections",
        "kind": "workflow",
        "phase": "verification",
        "description": "Applies ingested correction packages back into reduced-order configuration overrides.",
        "inputs": ["CFD correction packages", "design and CFD configs"],
        "outputs": ["corrected reduced-order settings", "correction impact summary"],
    },
    {
        "id": "test_plan",
        "title": "Test Plan",
        "kind": "workflow",
        "phase": "verification",
        "description": "Builds the coupon-to-full-scale campaign plan and initial test matrix.",
        "inputs": ["Design config", "Testing config", "geometry_definition.json", "injector geometry", "structural_sizing.json", "thermal_sizing.json", "nozzle_offdesign_results.json", "optional CFD campaign context", "nominal and optional 1D histories"],
        "outputs": ["testing/test_campaign_plan.json", "testing/test_matrix.csv", "testing overview SVGs"],
    },
    {
        "id": "test_define_articles",
        "title": "Test Articles",
        "kind": "workflow",
        "phase": "verification",
        "description": "Expands campaign stages into explicit test-article definitions and instrumentation expectations.",
        "inputs": ["Testing config", "campaign plan context", "geometry and hardware outputs"],
        "outputs": ["testing/test_articles.json", "instrumentation_plans.json"],
    },
    {
        "id": "test_ingest_data",
        "title": "Test Ingest",
        "kind": "workflow",
        "phase": "verification",
        "description": "Loads structured cold-flow or hot-fire data and converts it into reusable summaries.",
        "inputs": ["Testing config", "external rig or hot-fire datasets"],
        "outputs": ["testing/test_run_summaries.csv", "cleaned datasets", "feature extraction outputs"],
    },
    {
        "id": "test_compare_model",
        "title": "Model Vs Test",
        "kind": "workflow",
        "phase": "verification",
        "description": "Compares ingested test traces against the current reduced-order 0D or 1D model history.",
        "inputs": ["Testing config", "ingested test summaries", "nominal history", "optional internal_ballistics histories", "optional hot-fire calibration state"],
        "outputs": ["testing/model_vs_test_comparisons.csv", "comparison diagnostics"],
    },
    {
        "id": "test_calibrate_hotfire",
        "title": "Hot-Fire Calibrate",
        "kind": "workflow",
        "phase": "verification",
        "description": "Builds reusable regression, efficiency, and thermal calibration packages from test data.",
        "inputs": ["Testing config", "ingested hot-fire data", "model-vs-test comparisons"],
        "outputs": ["testing/hotfire_calibration_packages.json", "calibrated model hints"],
    },
    {
        "id": "test_readiness",
        "title": "Test Readiness",
        "kind": "workflow",
        "phase": "verification",
        "description": "Evaluates progression gates and reports whether the campaign is ready to advance to the next stage.",
        "inputs": ["Testing config", "campaign plan", "model-vs-test comparisons", "optional calibration packages", "optional CFD context"],
        "outputs": ["testing/readiness_summary.json", "testing/progression_gates.json", "readiness SVGs"],
    },
]


WORKFLOW_EDGES: list[dict[str, str]] = [
    {"from": "cea_config", "to": "cea", "label": "CEA sweep inputs"},
    {"from": "design_config", "to": "nominal", "label": "nominal design point"},
    {"from": "design_config", "to": "oat", "label": "perturbation baseline"},
    {"from": "design_config", "to": "corners", "label": "corner baseline"},
    {"from": "cea", "to": "geometry", "label": "CEA reference case"},
    {"from": "nominal", "to": "geometry", "label": "nominal metrics and history"},
    {"from": "oat", "to": "geometry", "label": "sensitivity rankings"},
    {"from": "corners", "to": "geometry", "label": "corner envelopes"},
    {"from": "geometry", "to": "internal_ballistics", "label": "geometry_definition.json"},
    {"from": "geometry", "to": "injector_design", "label": "frozen geometry"},
    {"from": "hydraulic_config", "to": "hydraulic_predict", "label": "dataset and compare settings"},
    {"from": "hydraulic_config", "to": "hydraulic_calibrate", "label": "calibration settings"},
    {"from": "hydraulic_config", "to": "hydraulic_compare", "label": "package selection"},
    {"from": "geometry", "to": "structural_size", "label": "geometry definition"},
    {"from": "nominal", "to": "structural_size", "label": "nominal loads"},
    {"from": "corners", "to": "structural_size", "label": "corner envelope loads"},
    {"from": "internal_ballistics", "to": "structural_size", "label": "optional 1D peak loads"},
    {"from": "injector_design", "to": "structural_size", "label": "injector geometry"},
    {"from": "structural_config", "to": "structural_size", "label": "structural policy"},
    {"from": "structural_size", "to": "thermal_size", "label": "structural_sizing.json"},
    {"from": "geometry", "to": "thermal_size", "label": "geometry definition"},
    {"from": "nominal", "to": "thermal_size", "label": "nominal heat-load history"},
    {"from": "internal_ballistics", "to": "thermal_size", "label": "optional 1D histories"},
    {"from": "thermal_config", "to": "thermal_size", "label": "thermal policy"},
    {"from": "thermal_size", "to": "nozzle_offdesign", "label": "thermal_sizing.json"},
    {"from": "structural_size", "to": "nozzle_offdesign", "label": "structural_sizing.json"},
    {"from": "geometry", "to": "nozzle_offdesign", "label": "geometry definition"},
    {"from": "nominal", "to": "nozzle_offdesign", "label": "nominal transient"},
    {"from": "corners", "to": "nozzle_offdesign", "label": "corner cases"},
    {"from": "nozzle_config", "to": "nozzle_offdesign", "label": "ambient cases and thresholds"},
    {"from": "nozzle_offdesign", "to": "cfd_plan", "label": "nozzle risks and environments"},
    {"from": "geometry", "to": "cfd_plan", "label": "geometry definition"},
    {"from": "injector_design", "to": "cfd_plan", "label": "injector geometry"},
    {"from": "structural_size", "to": "cfd_plan", "label": "hardware loads and margins"},
    {"from": "thermal_size", "to": "cfd_plan", "label": "thermal hotspots"},
    {"from": "cfd_config", "to": "cfd_plan", "label": "campaign settings"},
    {"from": "cfd_plan", "to": "cfd_export_cases", "label": "case definitions and targets"},
    {"from": "cfd_export_cases", "to": "cfd_ingest_results", "label": "case ids and expected outputs"},
    {"from": "cfd_ingest_results", "to": "cfd_apply_corrections", "label": "correction packages"},
    {"from": "cfd_plan", "to": "test_plan", "label": "optional CFD campaign context"},
    {"from": "nozzle_offdesign", "to": "test_plan", "label": "off-design readiness context"},
    {"from": "thermal_size", "to": "test_plan", "label": "thermal survivability"},
    {"from": "structural_size", "to": "test_plan", "label": "structural survivability"},
    {"from": "geometry", "to": "test_plan", "label": "geometry definition"},
    {"from": "injector_design", "to": "test_plan", "label": "injector article context"},
    {"from": "testing_config", "to": "test_plan", "label": "campaign settings"},
    {"from": "test_plan", "to": "test_define_articles", "label": "campaign stages and matrix"},
    {"from": "test_ingest_data", "to": "test_compare_model", "label": "ingested run summaries"},
    {"from": "nominal", "to": "test_compare_model", "label": "0D baseline"},
    {"from": "internal_ballistics", "to": "test_compare_model", "label": "optional 1D baseline"},
    {"from": "test_compare_model", "to": "test_calibrate_hotfire", "label": "comparison residuals"},
    {"from": "test_plan", "to": "test_readiness", "label": "campaign plan"},
    {"from": "test_compare_model", "to": "test_readiness", "label": "comparison evidence"},
    {"from": "test_calibrate_hotfire", "to": "test_readiness", "label": "calibration evidence"},
]


def workflow_map_payload() -> dict[str, Any]:
    return {
        "phases": WORKFLOW_PHASES,
        "nodes": WORKFLOW_NODES,
        "edges": WORKFLOW_EDGES,
    }
