"""Static workflow map metadata for the UI How To page."""

from __future__ import annotations

from typing import Any


def io_var(name: str, description: str, *, optional: bool = False) -> dict[str, Any]:
    return {"name": name, "description": description, "optional": optional}


WORKFLOW_PHASES: list[dict[str, str]] = [
    {"key": "configs", "title": "Config Inputs"},
    {"key": "performance", "title": "Performance And Analysis"},
    {"key": "geometry", "title": "Geometry And Flow Physics"},
    {"key": "hardware", "title": "Hardware Sizing"},
    {"key": "verification", "title": "Verification And Campaigns"},
]


WORKFLOW_NODES: list[dict[str, Any]] = [
    {
        "id": "design_config",
        "title": "Design Config",
        "kind": "config",
        "phase": "configs",
        "description": "Primary study definition for nominal performance, geometry, internal ballistics, and downstream hardware sizing.",
        "inputs": [],
        "outputs": [
            io_var("target_thrust_n", "Nominal thrust target requested by the study."),
            io_var("target_pc_bar", "Nominal chamber-pressure target used across the workflow."),
            io_var("burn_time_s", "Nominal burn duration used for transient studies."),
            io_var("oxidizer_name", "Selected oxidizer definition for the study."),
            io_var("fuel_name", "Selected fuel definition for the study."),
        ],
    },
    {
        "id": "cea_config",
        "title": "CEA Config",
        "kind": "config",
        "phase": "configs",
        "description": "Thermochemistry sweep settings, reactant setup, and area-ratio search controls.",
        "inputs": [],
        "outputs": [
            io_var("of_sweep_range", "Mixture-ratio sweep bounds used by the CEA study."),
            io_var("abs_volume_fraction_range", "ABS fuel-fraction sweep bounds for the hybrid fuel study."),
            io_var("ae_at_sweep_range", "Nozzle area-ratio sweep bounds used by CEA."),
            io_var("cea_chamber_pressure_pa", "CEA chamber-pressure setpoint for equilibrium calculations."),
        ],
    },
    {
        "id": "hydraulic_config",
        "title": "Hydraulic Config",
        "kind": "config",
        "phase": "configs",
        "description": "Rig dataset locations, calibration settings, and hydraulic comparison options.",
        "inputs": [],
        "outputs": [
            io_var("rig_dataset_path", "Cold-flow or hydraulic rig dataset root used for validation."),
            io_var("calibration_mode", "Selected hydraulic fitting strategy."),
            io_var("saved_calibration_package", "Reference hydraulic package to reuse during compare-only runs.", optional=True),
        ],
    },
    {
        "id": "structural_config",
        "title": "Structural Config",
        "kind": "config",
        "phase": "configs",
        "description": "Structural materials, load-source policy, closure sizing rules, and thickness limits.",
        "inputs": [],
        "outputs": [
            io_var("material_yield_strength_pa", "Primary allowable stress used for chamber and closure sizing."),
            io_var("minimum_wall_thickness_m", "Lower bound on wall thickness during first-pass sizing."),
            io_var("structural_safety_factor", "Required structural factor of safety."),
        ],
    },
    {
        "id": "thermal_config",
        "title": "Thermal Config",
        "kind": "config",
        "phase": "configs",
        "description": "Thermal load cases, allowable temperatures, and wall-model assumptions.",
        "inputs": [],
        "outputs": [
            io_var("allowable_wall_temp_k", "Maximum allowable wall temperature for survivability checks."),
            io_var("thermal_model_name", "Selected thermal correlation or wall model."),
            io_var("heat_flux_margin_factor", "Margin factor applied to thermal loading."),
        ],
    },
    {
        "id": "nozzle_config",
        "title": "Nozzle Off-Design Config",
        "kind": "config",
        "phase": "configs",
        "description": "Ambient environments, off-design checks, and recommendation thresholds.",
        "inputs": [],
        "outputs": [
            io_var("ambient_case_altitudes_m", "Altitude points used for discrete off-design nozzle checks."),
            io_var("include_vacuum_case", "Flag controlling whether a vacuum endpoint is included."),
            io_var("separation_risk_threshold", "Threshold used to classify nozzle separation risk."),
        ],
    },
    {
        "id": "cfd_config",
        "title": "CFD Config",
        "kind": "config",
        "phase": "configs",
        "description": "CFD campaign targets, case-export settings, and correction-ingest options.",
        "inputs": [],
        "outputs": [
            io_var("target_case_count", "Number of CFD targets requested for the campaign."),
            io_var("case_export_format", "Selected export format for CFD case packages."),
            io_var("correction_ingest_enabled", "Flag controlling whether CFD corrections are re-applied."),
        ],
    },
    {
        "id": "testing_config",
        "title": "Testing Config",
        "kind": "config",
        "phase": "configs",
        "description": "Campaign staging, dataset ingest rules, model-vs-test options, and readiness gates.",
        "inputs": [],
        "outputs": [
            io_var("stage_sequence", "Ordered set of campaign stages used by the testing workflow."),
            io_var("readiness_pass_threshold", "Threshold required to advance through readiness gates."),
            io_var("test_dataset_root", "Root directory for cold-flow or hot-fire datasets."),
        ],
    },
]

WORKFLOW_NODES.extend([
    {
        "id": "cea",
        "title": "Thermochemistry",
        "kind": "workflow",
        "phase": "performance",
        "description": "Runs NASA CEA sweeps and writes the highest-performance thermochemical state used downstream.",
        "inputs": [
            io_var("of_sweep_range", "Mixture-ratio sweep bounds used during the CEA study."),
            io_var("abs_volume_fraction_range", "ABS fraction sweep used for fuel trade studies."),
            io_var("ae_at_sweep_range", "Area-ratio sweep used for nozzle performance exploration."),
            io_var("cea_chamber_pressure_pa", "Chamber-pressure setpoint used for equilibrium evaluation."),
        ],
        "outputs": [
            io_var("isp_vac_s", "Vacuum specific impulse of the selected thermochemical state."),
            io_var("c_star_m_s", "Characteristic velocity for the selected thermochemical state."),
            io_var("gamma_exit", "Exit specific-heat ratio from the selected CEA solution."),
            io_var("molecular_weight_exit", "Exit molecular weight from the selected CEA solution."),
            io_var("combustion_temperature_k", "Combustion temperature associated with the selected solution."),
        ],
    },
    {
        "id": "nominal",
        "title": "Nominal Performance",
        "kind": "workflow",
        "phase": "performance",
        "description": "Runs the reduced-order 0D nominal case and produces the shared transient history used by many later steps.",
        "inputs": [
            io_var("target_thrust_n", "Nominal thrust target used to initialize the reduced-order run."),
            io_var("target_pc_bar", "Nominal chamber-pressure target used by the solver."),
            io_var("burn_time_s", "Nominal burn duration for the transient solution."),
            io_var("chamber_id_m", "Frozen chamber inner diameter if geometry already exists.", optional=True),
            io_var("injector_orifice_count", "Existing injector layout if injector geometry already exists.", optional=True),
            io_var("c_star_m_s", "Thermochemical characteristic velocity reused for the nominal run.", optional=True),
        ],
        "outputs": [
            io_var("pc_avg_bar", "Average chamber pressure over the nominal burn."),
            io_var("thrust_avg_n", "Average thrust over the nominal burn."),
            io_var("of_ratio_avg", "Average oxidizer-to-fuel ratio over the nominal burn."),
            io_var("total_impulse_ns", "Integrated impulse over the nominal burn."),
            io_var("burn_time_effective_s", "Effective burn time from the nominal history."),
        ],
    },
    {
        "id": "oat",
        "title": "Sensitivity",
        "kind": "workflow",
        "phase": "performance",
        "description": "One-at-a-time perturbation study used to identify dominant design drivers.",
        "inputs": [
            io_var("target_thrust_n", "Baseline thrust target used for the perturbation center point."),
            io_var("target_pc_bar", "Baseline chamber-pressure target used for perturbations."),
            io_var("burn_time_s", "Baseline burn duration used by the sensitivity run."),
        ],
        "outputs": [
            io_var("parameter_name", "Name of the perturbed design variable."),
            io_var("response_metric", "Metric monitored while measuring sensitivity impact."),
            io_var("delta_fraction", "Fractional response change caused by the perturbation."),
            io_var("sensitivity_rank", "Relative importance rank of the perturbed variable."),
        ],
    },
    {
        "id": "corners",
        "title": "Corner Cases",
        "kind": "workflow",
        "phase": "performance",
        "description": "Evaluates named hot, cold, and risk corners to create envelopes for geometry and hardware checks.",
        "inputs": [
            io_var("target_thrust_n", "Baseline thrust target used to define corner cases."),
            io_var("target_pc_bar", "Baseline chamber-pressure target used to define corner cases."),
            io_var("burn_time_s", "Baseline burn duration used to define corner transients."),
        ],
        "outputs": [
            io_var("corner_name", "Identifier of the evaluated corner case."),
            io_var("pc_peak_bar", "Peak chamber pressure reached in the corner case."),
            io_var("thrust_peak_n", "Peak thrust reached in the corner case."),
            io_var("of_ratio_corner", "Corner-case oxidizer-to-fuel ratio."),
            io_var("constraints_pass", "Flag showing whether the corner case stayed within constraints."),
        ],
    },
])

WORKFLOW_NODES.extend([
    {
        "id": "geometry",
        "title": "Geometry Freeze",
        "kind": "workflow",
        "phase": "geometry",
        "description": "Freezes the chamber, grain, injector-face, throat, and conical blended converging-throat-diverging nozzle geometry and records the variables used downstream.",
        "inputs": [
            io_var("target_thrust_n", "Design thrust target used to size the hardware."),
            io_var("target_pc_bar", "Design chamber pressure used to size the throat and chamber."),
            io_var("isp_vac_s", "Thermochemical vacuum specific impulse used in nozzle sizing."),
            io_var("c_star_m_s", "Thermochemical characteristic velocity used in sizing relations."),
            io_var("pc_avg_bar", "Nominal chamber-pressure level used to anchor geometry."),
            io_var("sensitivity_rank", "Optional sensitivity ranking used to highlight fragile dimensions.", optional=True),
            io_var("pc_peak_bar", "Optional corner-case pressure envelope used to make the frozen geometry robust.", optional=True),
        ],
        "outputs": [
            io_var("chamber_id_m", "Frozen chamber inner diameter."),
            io_var("throat_diameter_m", "Frozen throat diameter."),
            io_var("nozzle_exit_diameter_m", "Frozen nozzle exit diameter."),
            io_var("converging_section_length_m", "Frozen conical converging-section axial length."),
            io_var("nozzle_length_m", "Frozen conical nozzle axial length."),
            io_var("nozzle_contour_style", "Contour family recorded for the frozen converging-throat-diverging profile."),
            io_var("grain_length_m", "Frozen grain length."),
            io_var("port_radius_initial_m", "Initial fuel-port radius at ignition."),
        ],
    },
    {
        "id": "internal_ballistics",
        "title": "Internal Ballistics",
        "kind": "workflow",
        "phase": "geometry",
        "description": "Runs the quasi-1D solver with frozen geometry and produces transient ballistic histories.",
        "inputs": [
            io_var("target_pc_bar", "Target chamber pressure used to initialize the ballistic run."),
            io_var("burn_time_s", "Burn duration used for the quasi-1D transient window."),
            io_var("c_star_m_s", "Thermochemical characteristic velocity reused during the ballistic run."),
            io_var("chamber_id_m", "Frozen chamber diameter from the geometry step."),
            io_var("throat_diameter_m", "Frozen throat diameter from the geometry step."),
            io_var("injector_orifice_count", "Optional injector detail used when injector geometry is available.", optional=True),
        ],
        "outputs": [
            io_var("time_s", "Simulation time coordinate for the ballistic history."),
            io_var("pc_bar", "Instantaneous chamber pressure history."),
            io_var("thrust_n", "Instantaneous thrust history."),
            io_var("mdot_total_kg_s", "Total propellant mass-flow history."),
            io_var("port_radius_m", "Fuel-port radius history during regression."),
        ],
    },
    {
        "id": "injector_design",
        "title": "Injector Design",
        "kind": "workflow",
        "phase": "geometry",
        "description": "Synthesizes showerhead injector geometry and an effective reduced-order injector model.",
        "inputs": [
            io_var("target_thrust_n", "Thrust target used to estimate injector mass flow."),
            io_var("target_pc_bar", "Chamber-pressure target used to set injector pressure drop."),
            io_var("c_star_m_s", "Thermochemical characteristic velocity used for flow sizing."),
            io_var("chamber_id_m", "Injector-face packaging diameter from the frozen geometry."),
            io_var("throat_diameter_m", "Throat diameter used to keep injector sizing consistent with the nozzle."),
        ],
        "outputs": [
            io_var("injector_orifice_count", "Number of injector orifices in the selected design."),
            io_var("injector_orifice_diameter_m", "Diameter of each injector orifice."),
            io_var("injector_cd", "Discharge coefficient assumed by the reduced-order injector model."),
            io_var("injector_dp_bar", "Injector pressure-drop target used by the design."),
        ],
    },
    {
        "id": "hydraulic_predict",
        "title": "Hydraulic Predict",
        "kind": "workflow",
        "phase": "geometry",
        "description": "Compares measured hydraulic rig points against the current nominal feed and injector model.",
        "inputs": [
            io_var("rig_dataset_path", "Hydraulic dataset location used for the comparison."),
            io_var("injector_cd", "Current injector discharge coefficient used for prediction."),
            io_var("injector_orifice_count", "Current injector orifice count used in the reduced-order estimate.", optional=True),
            io_var("oxidizer_mass_flow_kg_s", "Measured or prescribed oxidizer flow points from the rig dataset."),
        ],
        "outputs": [
            io_var("predicted_dp_bar", "Predicted pressure drop across the hydraulic system."),
            io_var("measured_dp_bar", "Measured pressure drop from the rig dataset."),
            io_var("residual_fraction", "Fractional difference between prediction and measurement."),
            io_var("rmse_dp_bar", "Aggregate prediction error across the compared points."),
        ],
    },
    {
        "id": "hydraulic_calibrate",
        "title": "Hydraulic Calibrate",
        "kind": "workflow",
        "phase": "geometry",
        "description": "Fits feed and injector corrections and writes a reusable calibration package.",
        "inputs": [
            io_var("rig_dataset_path", "Hydraulic dataset used to fit the correction terms."),
            io_var("injector_cd", "Baseline injector discharge coefficient before calibration."),
            io_var("predicted_dp_bar", "Uncalibrated pressure-drop predictions."),
            io_var("measured_dp_bar", "Measured pressure-drop reference values."),
        ],
        "outputs": [
            io_var("line_loss_factor", "Fitted line-loss multiplier from the calibration pass."),
            io_var("injector_cd_calibrated", "Calibrated injector discharge coefficient."),
            io_var("rmse_dp_bar_calibrated", "Post-calibration hydraulic error metric."),
            io_var("calibration_quality_flag", "Flag showing whether the calibration met acceptance criteria."),
        ],
    },
    {
        "id": "hydraulic_compare",
        "title": "Hydraulic Compare",
        "kind": "workflow",
        "phase": "geometry",
        "description": "Loads a saved hydraulic calibration package and compares nominal versus corrected predictions.",
        "inputs": [
            io_var("saved_calibration_package", "Previously saved calibration package chosen for the comparison."),
            io_var("predicted_dp_bar", "Baseline predicted pressure-drop values before correction."),
            io_var("measured_dp_bar", "Measured hydraulic reference values."),
            io_var("line_loss_factor", "Correction multiplier loaded from the calibration package."),
        ],
        "outputs": [
            io_var("predicted_dp_nominal_bar", "Nominal pressure-drop prediction before correction."),
            io_var("predicted_dp_corrected_bar", "Corrected pressure-drop prediction after applying calibration."),
            io_var("improvement_fraction", "Fractional error improvement delivered by the correction package."),
            io_var("comparison_pass_flag", "Flag showing whether the corrected model outperformed the baseline."),
        ],
    },
])

WORKFLOW_NODES.extend([
    {
        "id": "structural_size",
        "title": "Structural Sizing",
        "kind": "workflow",
        "phase": "hardware",
        "description": "Sizes chamber shell, closures, injector plate, grain support, and first-pass structural mass.",
        "inputs": [
            io_var("material_yield_strength_pa", "Allowable structural stress used in the sizing rules."),
            io_var("minimum_wall_thickness_m", "Minimum structural thickness constraint."),
            io_var("structural_safety_factor", "Required structural factor of safety."),
            io_var("chamber_id_m", "Frozen chamber diameter to be sized structurally."),
            io_var("throat_diameter_m", "Frozen throat diameter used for nozzle and chamber sizing."),
            io_var("pc_avg_bar", "Nominal chamber-pressure load used for sizing."),
            io_var("pc_peak_bar", "Optional corner or ballistic peak pressure used for conservative sizing.", optional=True),
            io_var("injector_orifice_count", "Optional injector layout detail used during injector-plate sizing.", optional=True),
        ],
        "outputs": [
            io_var("shell_thickness_m", "Required chamber shell thickness."),
            io_var("closure_thickness_m", "Required closure thickness."),
            io_var("injector_plate_thickness_m", "Required injector-plate thickness."),
            io_var("total_structural_mass_estimate_kg", "First-pass structural mass estimate."),
            io_var("minimum_margin_of_safety", "Lowest structural margin reported by the sizing pass."),
        ],
    },
    {
        "id": "thermal_size",
        "title": "Thermal Sizing",
        "kind": "workflow",
        "phase": "hardware",
        "description": "Checks chamber, throat, nozzle, and injector-face thermal survivability using nominal and optional 1D histories.",
        "inputs": [
            io_var("allowable_wall_temp_k", "Allowable wall-temperature limit used for thermal survivability."),
            io_var("thermal_model_name", "Selected thermal model or correlation."),
            io_var("shell_thickness_m", "Structural wall thickness fed into the thermal wall stack."),
            io_var("chamber_id_m", "Frozen chamber diameter used to build thermal regions."),
            io_var("throat_diameter_m", "Frozen throat diameter used for thermal hotspot evaluation."),
            io_var("converging_section_length_m", "Frozen conical converging length used for throat-region bookkeeping."),
            io_var("nozzle_length_m", "Frozen conical nozzle length used for diverging-region bookkeeping."),
            io_var("pc_bar", "Nominal or quasi-1D chamber-pressure history."),
            io_var("mdot_total_kg_s", "Nominal or quasi-1D mass-flow history."),
            io_var("injector_orifice_count", "Optional injector detail used for injector-face thermal checks.", optional=True),
        ],
        "outputs": [
            io_var("peak_inner_wall_temp_k", "Peak inner-wall temperature across all thermal regions."),
            io_var("peak_heat_flux_w_m2", "Peak wall heat flux across all thermal regions."),
            io_var("minimum_margin_k", "Minimum remaining thermal margin to the allowable limit."),
            io_var("total_thermal_protection_mass_estimate_kg", "Estimated protection mass required by the thermal result."),
            io_var("governing_region_name", "Region that controlled the thermal design."),
        ],
    },
    {
        "id": "nozzle_offdesign",
        "title": "Nozzle Off-Design",
        "kind": "workflow",
        "phase": "hardware",
        "description": "Evaluates ambient sensitivity, separation risk, and recommended usage across ground and flight environments.",
        "inputs": [
            io_var("ambient_case_altitudes_m", "Altitude points used for the discrete off-design checks."),
            io_var("include_vacuum_case", "Flag controlling whether vacuum is included in the nozzle study."),
            io_var("separation_risk_threshold", "Threshold used to classify separation risk."),
            io_var("throat_diameter_m", "Frozen throat diameter used by the nozzle study."),
            io_var("nozzle_exit_diameter_m", "Frozen exit diameter used by the nozzle study."),
            io_var("pc_bar", "Nominal or quasi-1D chamber-pressure history used for operating-point extraction."),
            io_var("peak_inner_wall_temp_k", "Thermal hotspot context used for nozzle survivability recommendations."),
            io_var("minimum_margin_of_safety", "Structural margin context used for nozzle recommendations."),
        ],
        "outputs": [
            io_var("average_thrust_n", "Average thrust for each evaluated ambient case."),
            io_var("average_isp_s", "Average specific impulse for each ambient case."),
            io_var("separation_risk_level", "Categorical separation-risk classification for the ambient case."),
            io_var("recommended_usage_mode", "Recommended usage such as ground-test nozzle or baseline flight nozzle."),
            io_var("matched_altitude_m", "Altitude closest to matched expansion for the sampled environments."),
        ],
    },
])

WORKFLOW_NODES.extend([
    {
        "id": "cfd_plan",
        "title": "CFD Plan",
        "kind": "workflow",
        "phase": "verification",
        "description": "Builds the ordered CFD campaign, targets, operating points, and correction templates.",
        "inputs": [
            io_var("target_case_count", "Requested number of CFD targets."),
            io_var("case_export_format", "Selected CFD export format."),
            io_var("chamber_id_m", "Frozen chamber geometry used in CFD target planning."),
            io_var("throat_diameter_m", "Frozen throat diameter used in CFD target planning."),
            io_var("injector_orifice_count", "Injector pattern detail used in CFD targeting."),
            io_var("minimum_margin_of_safety", "Structural margin information used to prioritize CFD targets."),
            io_var("peak_inner_wall_temp_k", "Thermal hotspot information used to prioritize CFD targets."),
            io_var("separation_risk_level", "Nozzle risk classification used to prioritize CFD cases."),
            io_var("pc_bar", "Nominal or ballistic operating-point pressure history used to seed target conditions."),
        ],
        "outputs": [
            io_var("target_name", "Identifier of a selected CFD target."),
            io_var("priority_rank", "Priority rank assigned to the CFD target."),
            io_var("chamber_pressure_pa", "Representative chamber pressure for the target case."),
            io_var("mass_flow_kg_s", "Representative mass flow for the target case."),
            io_var("injector_inlet_pressure_pa", "Representative injector inlet pressure for the target case."),
        ],
    },
    {
        "id": "cfd_export_cases",
        "title": "CFD Export Cases",
        "kind": "workflow",
        "phase": "verification",
        "description": "Exports structured CFD case definitions, geometry packages, and boundary conditions for external solvers.",
        "inputs": [
            io_var("target_name", "Selected CFD target identifier."),
            io_var("chamber_pressure_pa", "Representative chamber pressure carried into the exported case."),
            io_var("mass_flow_kg_s", "Representative mass flow carried into the exported case."),
            io_var("injector_inlet_pressure_pa", "Injector inlet pressure used in the boundary conditions."),
            io_var("chamber_id_m", "Frozen chamber geometry exported into the case package."),
            io_var("throat_diameter_m", "Frozen throat geometry exported into the case package."),
            io_var("converging_section_length_m", "Frozen conical converging length exported into the case package."),
            io_var("nozzle_length_m", "Frozen conical nozzle length exported into the case package."),
        ],
        "outputs": [
            io_var("case_id", "Unique identifier of the exported CFD case."),
            io_var("boundary_condition_set", "Resolved boundary-condition set written for the external solver."),
            io_var("mesh_reference_id", "Reference mesh or geometry package id linked to the case."),
            io_var("ambient_pressure_pa", "Ambient pressure carried into the exported case."),
        ],
    },
    {
        "id": "cfd_ingest_results",
        "title": "CFD Ingest Results",
        "kind": "workflow",
        "phase": "verification",
        "description": "Loads summarized CFD outputs and converts them into reduced-order correction packages.",
        "inputs": [
            io_var("correction_ingest_enabled", "Flag controlling whether CFD corrections are expected."),
            io_var("case_id", "Identifier of the CFD case being ingested."),
            io_var("axial_pressure_profile_pa", "Extracted CFD pressure profile used for reduced-order corrections."),
            io_var("wall_heat_flux_w_m2", "Extracted CFD wall heat-flux information."),
            io_var("discharge_coefficient_delta", "Extracted CFD correction to effective injector discharge behavior."),
        ],
        "outputs": [
            io_var("pressure_loss_factor", "Reduced-order pressure-loss factor derived from the CFD data."),
            io_var("heat_transfer_multiplier", "Reduced-order thermal multiplier derived from the CFD data."),
            io_var("injector_cd_correction", "Correction to the reduced-order injector discharge coefficient."),
            io_var("nozzle_loss_coefficient", "CFD-derived nozzle loss coefficient."),
        ],
    },
    {
        "id": "cfd_apply_corrections",
        "title": "CFD Apply Corrections",
        "kind": "workflow",
        "phase": "verification",
        "description": "Applies ingested correction packages back into reduced-order configuration overrides.",
        "inputs": [
            io_var("pressure_loss_factor", "CFD-derived pressure-loss correction factor."),
            io_var("heat_transfer_multiplier", "CFD-derived thermal correction multiplier."),
            io_var("injector_cd_correction", "CFD-derived injector correction."),
            io_var("nozzle_loss_coefficient", "CFD-derived nozzle loss coefficient."),
            io_var("injector_cd", "Baseline injector discharge coefficient before correction."),
        ],
        "outputs": [
            io_var("corrected_pressure_loss_factor", "Pressure-loss factor after CFD correction is applied."),
            io_var("corrected_heat_transfer_multiplier", "Thermal multiplier after CFD correction is applied."),
            io_var("corrected_injector_cd", "Injector discharge coefficient after CFD correction is applied."),
            io_var("corrected_nozzle_loss_coefficient", "Nozzle loss coefficient after CFD correction is applied."),
        ],
    },
    {
        "id": "test_plan",
        "title": "Test Plan",
        "kind": "workflow",
        "phase": "verification",
        "description": "Builds the coupon-to-full-scale campaign plan and initial test matrix.",
        "inputs": [
            io_var("stage_sequence", "Ordered testing stages from the campaign configuration."),
            io_var("readiness_pass_threshold", "Readiness threshold that must be respected by the campaign plan."),
            io_var("chamber_id_m", "Frozen geometry used to define test-article size class."),
            io_var("injector_orifice_count", "Injector article detail carried into the test plan."),
            io_var("total_structural_mass_estimate_kg", "Structural context used to scope the campaign."),
            io_var("minimum_margin_k", "Thermal context used to scope the campaign."),
            io_var("recommended_usage_mode", "Nozzle recommendation used to decide article variants."),
            io_var("thrust_avg_n", "Nominal thrust expectation used to seed test objectives."),
        ],
        "outputs": [
            io_var("stage_name", "Name of the planned test stage."),
            io_var("point_id", "Identifier of a planned test point."),
            io_var("expected_burn_time_s", "Expected burn duration for the planned test point."),
            io_var("objective", "Primary purpose of the planned test point."),
            io_var("required_instrumentation_set", "Instrumentation required for the planned test point."),
        ],
    },
    {
        "id": "test_define_articles",
        "title": "Test Articles",
        "kind": "workflow",
        "phase": "verification",
        "description": "Expands campaign stages into explicit test-article definitions and instrumentation expectations.",
        "inputs": [
            io_var("stage_name", "Campaign stage being expanded into explicit hardware articles."),
            io_var("point_id", "Planned test point that the article must support."),
            io_var("chamber_id_m", "Frozen chamber geometry used to define the article hardware."),
            io_var("shell_thickness_m", "Structural chamber thickness used in the article definition."),
            io_var("minimum_margin_k", "Thermal margin used to decide protection and instrumentation needs."),
            io_var("injector_orifice_count", "Injector configuration carried into the article definition.", optional=True),
        ],
        "outputs": [
            io_var("article_id", "Identifier of the explicit hardware article."),
            io_var("hardware_configuration", "Resolved hardware configuration of the article."),
            io_var("instrumentation_channel_count", "Number of required measurement channels for the article."),
            io_var("acceptance_criteria", "Acceptance criteria attached to the article or stage."),
        ],
    },
])

WORKFLOW_NODES.extend([
    {
        "id": "test_ingest_data",
        "title": "Test Ingest",
        "kind": "workflow",
        "phase": "verification",
        "description": "Loads structured cold-flow or hot-fire data and converts it into reusable summaries.",
        "inputs": [
            io_var("test_dataset_root", "Root directory of the external test data."),
            io_var("stage_name", "Campaign stage used to interpret the incoming dataset."),
            io_var("point_id", "Test-point identifier used to align imported traces."),
        ],
        "outputs": [
            io_var("thrust_peak_n", "Peak thrust extracted from the ingested dataset."),
            io_var("pc_peak_bar", "Peak chamber pressure extracted from the ingested dataset."),
            io_var("burn_time_test_s", "Burn duration extracted from the ingested dataset."),
            io_var("impulse_test_ns", "Impulse extracted from the ingested dataset."),
            io_var("ignition_delay_s", "Ignition delay extracted from the ingested dataset."),
        ],
    },
    {
        "id": "test_compare_model",
        "title": "Model Vs Test",
        "kind": "workflow",
        "phase": "verification",
        "description": "Compares ingested test traces against the current reduced-order 0D or 1D model history.",
        "inputs": [
            io_var("thrust_peak_n", "Measured thrust peak from the ingested dataset."),
            io_var("pc_peak_bar", "Measured chamber-pressure peak from the ingested dataset."),
            io_var("burn_time_test_s", "Measured burn duration from the ingested dataset."),
            io_var("thrust_avg_n", "Predicted nominal thrust used as the model baseline."),
            io_var("pc_avg_bar", "Predicted nominal chamber pressure used as the model baseline."),
            io_var("thrust_n", "Optional quasi-1D thrust history used for richer comparison.", optional=True),
        ],
        "outputs": [
            io_var("thrust_rmse_n", "Root-mean-square thrust error between model and test."),
            io_var("pc_rmse_bar", "Root-mean-square chamber-pressure error between model and test."),
            io_var("burn_time_error_s", "Difference between predicted and measured burn duration."),
            io_var("agreement_flag", "Flag showing whether the model met the comparison threshold."),
        ],
    },
    {
        "id": "test_calibrate_hotfire",
        "title": "Hot-Fire Calibrate",
        "kind": "workflow",
        "phase": "verification",
        "description": "Builds reusable regression, efficiency, and thermal calibration packages from test data.",
        "inputs": [
            io_var("thrust_rmse_n", "Model-versus-test thrust error used for calibration."),
            io_var("pc_rmse_bar", "Model-versus-test chamber-pressure error used for calibration."),
            io_var("burn_time_error_s", "Burn-duration mismatch used during calibration."),
            io_var("peak_inner_wall_temp_k", "Thermal response used when calibrating heat-transfer bias.", optional=True),
        ],
        "outputs": [
            io_var("combustion_efficiency_scale", "Calibration factor applied to combustion efficiency."),
            io_var("regression_rate_scale", "Calibration factor applied to regression rate."),
            io_var("heat_transfer_bias_factor", "Calibration factor applied to heat-transfer estimates."),
            io_var("fit_quality_score", "Aggregate score describing calibration quality."),
        ],
    },
    {
        "id": "test_readiness",
        "title": "Test Readiness",
        "kind": "workflow",
        "phase": "verification",
        "description": "Evaluates progression gates and reports whether the campaign is ready to advance to the next stage.",
        "inputs": [
            io_var("readiness_pass_threshold", "Threshold used to decide whether the campaign can advance."),
            io_var("agreement_flag", "Model-versus-test agreement status."),
            io_var("fit_quality_score", "Calibration quality score used as readiness evidence.", optional=True),
            io_var("priority_rank", "Optional CFD support priority used when readiness depends on CFD evidence.", optional=True),
            io_var("stage_name", "Current campaign stage under readiness review."),
        ],
        "outputs": [
            io_var("overall_readiness_flag", "Overall readiness decision for the current campaign stage."),
            io_var("recommended_next_stage", "Next campaign stage recommended by the readiness logic."),
            io_var("blocking_gate_name", "Name of the gate currently blocking progress, if any."),
            io_var("evidence_gap_count", "Number of missing evidence items before progression is allowed."),
        ],
    },
])


WORKFLOW_EDGES: list[dict[str, str]] = [
    {"from": "cea_config", "to": "cea", "label": "of_sweep_range, ae_at_sweep_range"},
    {"from": "design_config", "to": "nominal", "label": "target_thrust_n, target_pc_bar"},
    {"from": "design_config", "to": "oat", "label": "target_thrust_n, burn_time_s"},
    {"from": "design_config", "to": "corners", "label": "target_pc_bar, burn_time_s"},
    {"from": "cea", "to": "geometry", "label": "isp_vac_s, c_star_m_s"},
    {"from": "nominal", "to": "geometry", "label": "pc_avg_bar, thrust_avg_n"},
    {"from": "oat", "to": "geometry", "label": "sensitivity_rank"},
    {"from": "corners", "to": "geometry", "label": "pc_peak_bar, thrust_peak_n"},
    {"from": "geometry", "to": "internal_ballistics", "label": "chamber_id_m, throat_diameter_m"},
    {"from": "geometry", "to": "injector_design", "label": "chamber_id_m, throat_diameter_m"},
    {"from": "hydraulic_config", "to": "hydraulic_predict", "label": "rig_dataset_path, calibration_mode"},
    {"from": "hydraulic_config", "to": "hydraulic_calibrate", "label": "rig_dataset_path, calibration_mode"},
    {"from": "hydraulic_config", "to": "hydraulic_compare", "label": "saved_calibration_package"},
    {"from": "geometry", "to": "structural_size", "label": "chamber_id_m, throat_diameter_m"},
    {"from": "nominal", "to": "structural_size", "label": "pc_avg_bar, thrust_avg_n"},
    {"from": "corners", "to": "structural_size", "label": "pc_peak_bar, thrust_peak_n"},
    {"from": "internal_ballistics", "to": "structural_size", "label": "pc_bar, mdot_total_kg_s"},
    {"from": "injector_design", "to": "structural_size", "label": "injector_orifice_count, injector_dp_bar"},
    {"from": "structural_config", "to": "structural_size", "label": "material_yield_strength_pa, structural_safety_factor"},
    {"from": "structural_size", "to": "thermal_size", "label": "shell_thickness_m, minimum_margin_of_safety"},
    {"from": "geometry", "to": "thermal_size", "label": "chamber_id_m, throat_diameter_m"},
    {"from": "nominal", "to": "thermal_size", "label": "pc_avg_bar, thrust_avg_n"},
    {"from": "internal_ballistics", "to": "thermal_size", "label": "pc_bar, mdot_total_kg_s"},
    {"from": "thermal_config", "to": "thermal_size", "label": "allowable_wall_temp_k, thermal_model_name"},
    {"from": "thermal_size", "to": "nozzle_offdesign", "label": "peak_inner_wall_temp_k, minimum_margin_k"},
    {"from": "structural_size", "to": "nozzle_offdesign", "label": "minimum_margin_of_safety, shell_thickness_m"},
    {"from": "geometry", "to": "nozzle_offdesign", "label": "throat_diameter_m, nozzle_exit_diameter_m"},
    {"from": "nominal", "to": "nozzle_offdesign", "label": "pc_avg_bar, thrust_avg_n"},
    {"from": "corners", "to": "nozzle_offdesign", "label": "pc_peak_bar, thrust_peak_n"},
    {"from": "nozzle_config", "to": "nozzle_offdesign", "label": "ambient_case_altitudes_m, separation_risk_threshold"},
    {"from": "nozzle_offdesign", "to": "cfd_plan", "label": "average_thrust_n, separation_risk_level"},
    {"from": "geometry", "to": "cfd_plan", "label": "chamber_id_m, throat_diameter_m"},
    {"from": "injector_design", "to": "cfd_plan", "label": "injector_orifice_count, injector_cd"},
    {"from": "structural_size", "to": "cfd_plan", "label": "minimum_margin_of_safety, shell_thickness_m"},
    {"from": "thermal_size", "to": "cfd_plan", "label": "peak_inner_wall_temp_k, minimum_margin_k"},
    {"from": "cfd_config", "to": "cfd_plan", "label": "target_case_count, case_export_format"},
    {"from": "cfd_plan", "to": "cfd_export_cases", "label": "target_name, chamber_pressure_pa"},
    {"from": "cfd_export_cases", "to": "cfd_ingest_results", "label": "case_id, boundary_condition_set"},
    {"from": "cfd_ingest_results", "to": "cfd_apply_corrections", "label": "pressure_loss_factor, heat_transfer_multiplier"},
    {"from": "cfd_plan", "to": "test_plan", "label": "target_name, priority_rank"},
    {"from": "nozzle_offdesign", "to": "test_plan", "label": "recommended_usage_mode, average_thrust_n"},
    {"from": "thermal_size", "to": "test_plan", "label": "minimum_margin_k, peak_inner_wall_temp_k"},
    {"from": "structural_size", "to": "test_plan", "label": "minimum_margin_of_safety, total_structural_mass_estimate_kg"},
    {"from": "geometry", "to": "test_plan", "label": "chamber_id_m, nozzle_exit_diameter_m"},
    {"from": "injector_design", "to": "test_plan", "label": "injector_orifice_count, injector_orifice_diameter_m"},
    {"from": "testing_config", "to": "test_plan", "label": "stage_sequence, readiness_pass_threshold"},
    {"from": "test_plan", "to": "test_define_articles", "label": "stage_name, point_id"},
    {"from": "test_ingest_data", "to": "test_compare_model", "label": "thrust_peak_n, pc_peak_bar"},
    {"from": "nominal", "to": "test_compare_model", "label": "thrust_avg_n, pc_avg_bar"},
    {"from": "internal_ballistics", "to": "test_compare_model", "label": "thrust_n, pc_bar"},
    {"from": "test_compare_model", "to": "test_calibrate_hotfire", "label": "thrust_rmse_n, pc_rmse_bar"},
    {"from": "test_plan", "to": "test_readiness", "label": "stage_name, expected_burn_time_s"},
    {"from": "test_compare_model", "to": "test_readiness", "label": "agreement_flag, burn_time_error_s"},
    {"from": "test_calibrate_hotfire", "to": "test_readiness", "label": "fit_quality_score, combustion_efficiency_scale"},
]


def workflow_map_payload() -> dict[str, Any]:
    return {
        "phases": WORKFLOW_PHASES,
        "nodes": [{**node, "detail_href": f"/simulation.html?step={node['id']}"} for node in WORKFLOW_NODES],
        "edges": WORKFLOW_EDGES,
    }
