"""Labels for blowdown-specific fields exposed to the UI."""

from cea_hybrid.labels import metric_label as cea_metric_label


VARIABLE_LABELS = {
    "model_name": "Simulation Name",
    "ui_mode": "UI Mode",
    "seed_case_source": "CEA Seed Case",
    "seed_target_thrust_n": "Seed Reference Thrust [N]",
    "seed_isp_s": "Seed Legacy Isp [s]",
    "seed_isp_sl_s": "Seed Sea-Level Isp [s]",
    "seed_isp_vac_s": "Seed Vacuum Isp [s]",
    "seed_of_ratio": "Seed O/F [-]",
    "seed_pc_bar": "Seed Chamber Pressure [bar]",
    "seed_oxidizer_temp_k": "Seed Oxidizer Temperature [K]",
    "seed_fuel_temp_k": "Seed Fuel Temperature [K]",
    "seed_abs_volume_fraction": "Seed ABS Volume Fraction [-]",
    "seed_abs_mass_fraction": "Seed ABS Mass Fraction [-]",
    "seed_cf_sea_level": "Seed Sea-Level Cf [-]",
    "seed_cf_vac": "Seed Vacuum Cf [-]",
    "seed_cstar_mps": "Seed c* [m/s]",
    "seed_thrust_sea_level_n": "Seed Sea-Level Thrust [N]",
    "seed_thrust_vac_n": "Seed Vacuum Thrust [N]",
    "abs_density_kg_m3": "ABS Density [kg/m^3]",
    "paraffin_density_kg_m3": "Paraffin Density [kg/m^3]",
    "target_mdot_total_kg_s": "Target Mass Flow [kg/s]",
    "target_mdot_ox_kg_s": "Target Oxidizer Flow [kg/s]",
    "target_mdot_f_kg_s": "Target Fuel Flow [kg/s]",
    "target_of_ratio": "Target O/F [-]",
    "target_pc_bar": "Target Chamber Pressure [bar]",
    "required_oxidizer_mass_kg": "Required Oxidizer Mass [kg]",
    "loaded_oxidizer_mass_kg": "Loaded Oxidizer Mass [kg]",
    "tank_sizing_mode": "Tank Sizing Mode",
    "tank_initial_fill_fraction": "Initial Fill Fraction [-]",
    "tank_usable_oxidizer_fraction": "Usable Oxidizer Fraction [-]",
    "tank_oxidizer_liquid_volume_l": "Loaded Oxidizer Liquid Volume [L]",
    "tank_volume_l": "Tank Volume [L]",
    "tank_initial_mass_kg": "Initial Tank Mass [kg]",
    "tank_initial_temp_k": "Tank Initial Temperature [K]",
    "tank_initial_pressure_bar": "Initial Tank Pressure [bar]",
    "tank_mass_volume_source": "Tank Mass/Volume Source",
    "tank_volume_source": "Tank Volume Source",
    "tank_usable_fraction_source": "Usable Oxidizer Fraction Source",
    "tank_reserve_mass_kg": "Reserved Oxidizer Mass [kg]",
    "injector_sizing_mode": "Injector Sizing Mode",
    "fuel_density_kg_m3": "Fuel Blend Density [kg/m^3]",
    "regression_preset": "Regression Preset",
    "regression_a_si": "Regression Coefficient a [SI]",
    "regression_n": "Regression Exponent n [-]",
    "regression_source": "Regression Source",
    "port_count": "Port Count",
    "port_count_source": "Port Count Source",
    "target_initial_gox_kg_m2_s": "Target Initial Gox [kg/m^2/s]",
    "initial_port_area_mm2": "Initial Port Area [mm^2]",
    "initial_port_radius_mm": "Initial Port Radius [mm]",
    "initial_port_source": "Initial Port Source",
    "initial_regression_rate_mm_s": "Initial Regression Rate [mm/s]",
    "required_fuel_mass_kg": "Required Fuel Mass [kg]",
    "loaded_fuel_mass_kg": "Loaded Fuel Mass [kg]",
    "fuel_usable_fraction": "Fuel Usable Fraction [-]",
    "fuel_usable_fraction_source": "Fuel Usable Fraction Source",
    "grain_outer_radius_mm": "Outer Grain Radius [mm]",
    "grain_length_source": "Grain Length Source",
    "outer_radius_source": "Outer Radius Source",
    "injector_cd": "Injector Cd [-]",
    "injector_cd_source": "Injector Cd Source",
    "injector_hole_count": "Injector Hole Count",
    "injector_hole_count_source": "Injector Hole Count Source",
    "injector_pressure_drop_policy": "Injector Pressure-Drop Policy",
    "injector_sizing_condition": "Injector Sizing Condition",
    "injector_minimum_dp_over_pc": "Injector Minimum dP / Pc [-]",
    "injector_delta_p_mode": "Injector Delta-p Mode",
    "injector_delta_p_source": "Injector Delta-p Source",
    "injector_delta_p_fraction_of_pc": "Injector Delta-p / Pc [-]",
    "injector_delta_p_bar": "Injector Delta-p [bar]",
    "injector_total_area_mm2": "Injector Total Area [mm^2]",
    "injector_total_area_source": "Injector Total Area Source",
    "injector_area_per_hole_mm2": "Injector Area per Hole [mm^2]",
    "injector_hole_diameter_mm": "Equivalent Hole Diameter [mm]",
    "feed_line_id_mm": "Feed Line ID [mm]",
    "feed_line_length_m": "Feed Line Length [m]",
    "feed_friction_factor": "Feed Friction Factor [-]",
    "feed_minor_loss_k_total": "Feed Minor Loss K [-]",
    "feed_loss_model": "Feed Loss Model",
    "feed_pressure_drop_multiplier": "Feed dP Multiplier [-]",
    "feed_manual_delta_p_bar": "Manual Feed dP [bar]",
    "feed_loss_source": "Feed Loss Source",
    "grain_length_m": "Grain Length [m]",
    "design_tank_pressure_bar": "Design Tank Pressure [bar]",
    "design_liquid_density_kg_m3": "Design Liquid Density [kg/m^3]",
    "design_injector_inlet_pressure_bar": "Design Injector Inlet Pressure [bar]",
    "design_feed_pressure_drop_bar": "Design Feed Pressure Drop [bar]",
    "design_injector_delta_p_bar": "Design Injector Delta-p [bar]",
    "design_dp_feed_over_pc": "Design Feed dP / Pc [-]",
    "design_dp_injector_over_pc": "Design Injector dP / Pc [-]",
    "design_dp_total_over_ptank": "Design Total dP / Ptank [-]",
    "design_injector_to_feed_dp_ratio": "Design Injector dP / Feed dP [-]",
    "design_injector_dominant": "Design Injector Dominant Restriction",
    "nozzle_throat_area_mm2": "Nozzle Throat Area [mm^2]",
    "nozzle_exit_area_mm2": "Nozzle Exit Area [mm^2]",
    "nozzle_cstar_mps": "Design c* [m/s]",
    "nozzle_cf_sea_level": "Design Sea-Level Cf [-]",
    "nozzle_cf_vac": "Design Vacuum Cf [-]",
    "geometry_valid": "Geometry Valid",
    "geometry_warnings": "Geometry Warnings",
    "geometry_suggestions": "Geometry Suggestions",
    "initial_radial_web_mm": "Initial Radial Web [mm]",
    "initial_port_to_outer_radius_ratio": "Initial Port / Outer Radius [-]",
    "grain_slenderness_ratio": "Grain Slenderness Ratio [-]",
    "stop_reason": "Stop Reason",
    "simulated_time_s": "Simulated Time [s]",
    "step_count": "Time Steps",
    "burn_time_target_met": "Burn Duration Target Met",
    "remaining_oxidizer_reserve_kg": "Remaining Oxidizer Reserve [kg]",
    "injector_dominant_over_feed": "Injector Dominant Over Feed",
    "initial_tank_pressure_bar": "Simulated Initial Tank Pressure [bar]",
    "final_tank_pressure_bar": "Simulated Final Tank Pressure [bar]",
    "initial_tank_temperature_k": "Simulated Initial Tank Temperature [K]",
    "final_tank_temperature_k": "Simulated Final Tank Temperature [K]",
    "initial_chamber_pressure_bar": "Simulated Initial Chamber Pressure [bar]",
    "final_chamber_pressure_bar": "Simulated Final Chamber Pressure [bar]",
    "initial_injector_inlet_pressure_bar": "Simulated Initial Injector Inlet Pressure [bar]",
    "final_injector_inlet_pressure_bar": "Simulated Final Injector Inlet Pressure [bar]",
    "initial_feed_pressure_drop_bar": "Simulated Initial Feed Pressure Drop [bar]",
    "final_feed_pressure_drop_bar": "Simulated Final Feed Pressure Drop [bar]",
    "initial_injector_delta_p_bar": "Simulated Initial Injector Delta-p [bar]",
    "final_injector_delta_p_bar": "Simulated Final Injector Delta-p [bar]",
    "initial_dp_feed_over_pc": "Simulated Initial Feed dP / Pc [-]",
    "final_dp_feed_over_pc": "Simulated Final Feed dP / Pc [-]",
    "initial_dp_injector_over_pc": "Simulated Initial Injector dP / Pc [-]",
    "final_dp_injector_over_pc": "Simulated Final Injector dP / Pc [-]",
    "initial_dp_total_over_ptank": "Simulated Initial Total dP / Ptank [-]",
    "final_dp_total_over_ptank": "Simulated Final Total dP / Ptank [-]",
    "initial_injector_to_feed_dp_ratio": "Simulated Initial Injector dP / Feed dP [-]",
    "final_injector_to_feed_dp_ratio": "Simulated Final Injector dP / Feed dP [-]",
    "initial_thrust_n": "Simulated Initial Actual Thrust [N]",
    "final_thrust_n": "Simulated Final Actual Thrust [N]",
    "initial_thrust_vac_n": "Simulated Initial Vacuum Thrust [N]",
    "final_thrust_vac_n": "Simulated Final Vacuum Thrust [N]",
    "initial_isp_s": "Simulated Initial Actual Isp [s]",
    "final_isp_s": "Simulated Final Actual Isp [s]",
    "initial_isp_vac_s": "Simulated Initial Vacuum Isp [s]",
    "final_isp_vac_s": "Simulated Final Vacuum Isp [s]",
    "initial_cf_actual": "Simulated Initial Actual Cf [-]",
    "final_cf_actual": "Simulated Final Actual Cf [-]",
    "initial_cf_vac": "Simulated Initial Vacuum Cf [-]",
    "final_cf_vac": "Simulated Final Vacuum Cf [-]",
    "initial_cstar_mps": "Simulated Initial c* [m/s]",
    "final_cstar_mps": "Simulated Final c* [m/s]",
    "initial_of_ratio": "Simulated Initial O/F [-]",
    "final_of_ratio": "Simulated Final O/F [-]",
    "initial_mdot_ox_kg_s": "Simulated Initial Oxidizer Flow [kg/s]",
    "final_mdot_ox_kg_s": "Simulated Final Oxidizer Flow [kg/s]",
    "initial_mdot_f_kg_s": "Simulated Initial Fuel Flow [kg/s]",
    "final_mdot_f_kg_s": "Simulated Final Fuel Flow [kg/s]",
    "initial_mdot_total_kg_s": "Simulated Initial Total Flow [kg/s]",
    "final_mdot_total_kg_s": "Simulated Final Total Flow [kg/s]",
    "initial_oxidizer_flux_kg_m2_s": "Simulated Initial Oxidizer Flux [kg/m^2/s]",
    "final_oxidizer_flux_kg_m2_s": "Simulated Final Oxidizer Flux [kg/m^2/s]",
    "initial_regression_rate_mm_s": "Simulated Initial Regression Rate [mm/s]",
    "final_regression_rate_mm_s": "Simulated Final Regression Rate [mm/s]",
    "initial_liquid_density_kg_m3": "Simulated Initial Liquid Density [kg/m^3]",
    "final_liquid_density_kg_m3": "Simulated Final Liquid Density [kg/m^3]",
    "initial_port_diameter_mm": "Simulated Initial Port Diameter [mm]",
    "final_port_diameter_mm": "Simulated Final Port Diameter [mm]",
    "initial_tank_quality": "Simulated Initial Tank Quality [-]",
    "final_tank_quality": "Simulated Final Tank Quality [-]",
    "initial_exit_pressure_bar": "Simulated Initial Exit Pressure [bar]",
    "final_exit_pressure_bar": "Simulated Final Exit Pressure [bar]",
    "initial_gamma_e": "Simulated Initial Exit Gamma [-]",
    "final_gamma_e": "Simulated Final Exit Gamma [-]",
    "initial_molecular_weight_exit": "Simulated Initial Exit Molecular Weight",
    "final_molecular_weight_exit": "Simulated Final Exit Molecular Weight",
    "simulation_burn_time_s": "Simulation Burn Time [s]",
    "simulation_dt_s": "Simulation dt [s]",
    "simulation_ambient_pressure_bar": "Ambient Pressure [bar]",
    "simulation_max_inner_iterations": "Max Inner Iterations",
    "simulation_relaxation": "Simulation Relaxation [-]",
    "simulation_relative_tolerance": "Simulation Relative Tolerance [-]",
    "simulation_tank_quality_cutoff": "Tank Quality Cutoff [-]",
    "simulation_oxidizer_depletion_policy": "Oxidizer Depletion Policy",
    "simulation_stop_on_quality_limit": "Stop On Quality Limit",
    "performance_lookup_active": "Dynamic Performance Lookup Active",
    "performance_lookup_warning": "Dynamic Performance Lookup Warning",
}


def variable_label(key):
    return VARIABLE_LABELS.get(key, cea_metric_label(key))
