"""Labels for blowdown-specific fields exposed to the UI."""

from cea_hybrid.labels import metric_label as cea_metric_label


VARIABLE_LABELS = {
    "model_name": "Simulation Name",
    "ui_mode": "UI Mode",
    "seed_case_source": "CEA Seed Case",
    "seed_target_thrust_n": "Seed Target Thrust [N]",
    "seed_isp_s": "Seed Isp [s]",
    "seed_of_ratio": "Seed O/F [-]",
    "seed_pc_bar": "Seed Chamber Pressure [bar]",
    "seed_oxidizer_temp_k": "Seed Oxidizer Temperature [K]",
    "seed_fuel_temp_k": "Seed Fuel Temperature [K]",
    "seed_abs_volume_fraction": "Seed ABS Volume Fraction [-]",
    "seed_abs_mass_fraction": "Seed ABS Mass Fraction [-]",
    "target_mdot_total_kg_s": "Target Mass Flow [kg/s]",
    "target_mdot_ox_kg_s": "Target Oxidizer Flow [kg/s]",
    "target_mdot_f_kg_s": "Target Fuel Flow [kg/s]",
    "target_of_ratio": "Target O/F [-]",
    "target_pc_bar": "Target Chamber Pressure [bar]",
    "required_oxidizer_mass_kg": "Required Oxidizer Mass [kg]",
    "loaded_oxidizer_mass_kg": "Loaded Oxidizer Mass [kg]",
    "tank_sizing_mode": "Tank Sizing Mode",
    "tank_initial_fill_fraction": "Initial Fill Fraction [-]",
    "tank_usable_oxidizer_fraction": "Usable Oxidizer Fraction [-]",
    "tank_oxidizer_liquid_volume_l": "Loaded Oxidizer Liquid Volume [L]",
    "tank_volume_l": "Tank Volume [L]",
    "tank_initial_mass_kg": "Initial Tank Mass [kg]",
    "tank_initial_temp_k": "Tank Initial Temperature [K]",
    "tank_mass_volume_source": "Tank Mass/Volume Source",
    "tank_volume_source": "Tank Volume Source",
    "injector_sizing_mode": "Injector Sizing Mode",
    "fuel_density_kg_m3": "Fuel Blend Density [kg/m^3]",
    "target_initial_gox_kg_m2_s": "Target Initial Gox [kg/m^2/s]",
    "initial_port_area_mm2": "Initial Port Area [mm^2]",
    "initial_port_radius_mm": "Initial Port Radius [mm]",
    "initial_port_source": "Initial Port Source",
    "initial_regression_rate_mm_s": "Initial Regression Rate [mm/s]",
    "required_fuel_mass_kg": "Required Fuel Mass [kg]",
    "loaded_fuel_mass_kg": "Loaded Fuel Mass [kg]",
    "fuel_usable_fraction": "Fuel Usable Fraction [-]",
    "grain_outer_radius_mm": "Outer Grain Radius [mm]",
    "grain_length_source": "Grain Length Source",
    "outer_radius_source": "Outer Radius Source",
    "injector_cd": "Injector Cd [-]",
    "injector_hole_count": "Injector Hole Count",
    "injector_delta_p_mode": "Injector Delta-p Mode",
    "injector_delta_p_bar": "Injector Delta-p [bar]",
    "injector_total_area_mm2": "Injector Total Area [mm^2]",
    "injector_total_area_source": "Injector Total Area Source",
    "injector_area_per_hole_mm2": "Injector Area per Hole [mm^2]",
    "injector_hole_diameter_mm": "Equivalent Hole Diameter [mm]",
    "grain_length_m": "Grain Length [m]",
    "design_tank_pressure_bar": "Design Tank Pressure [bar]",
    "design_liquid_density_kg_m3": "Design Liquid Density [kg/m^3]",
    "design_injector_inlet_pressure_bar": "Design Injector Inlet Pressure [bar]",
    "design_feed_pressure_drop_bar": "Design Feed Pressure Drop [bar]",
    "design_injector_delta_p_bar": "Design Injector Delta-p [bar]",
    "nozzle_throat_area_mm2": "Nozzle Throat Area [mm^2]",
    "nozzle_exit_area_mm2": "Nozzle Exit Area [mm^2]",
    "nozzle_cstar_mps": "Seed c* [m/s]",
    "nozzle_cf": "Seed Cf [-]",
    "stop_reason": "Stop Reason",
    "simulated_time_s": "Simulated Time [s]",
    "step_count": "Time Steps",
    "initial_tank_pressure_bar": "Initial Tank Pressure [bar]",
    "final_tank_pressure_bar": "Final Tank Pressure [bar]",
    "initial_tank_temperature_k": "Initial Tank Temperature [K]",
    "final_tank_temperature_k": "Final Tank Temperature [K]",
    "initial_chamber_pressure_bar": "Initial Chamber Pressure [bar]",
    "final_chamber_pressure_bar": "Final Chamber Pressure [bar]",
    "initial_injector_inlet_pressure_bar": "Initial Injector Inlet Pressure [bar]",
    "final_injector_inlet_pressure_bar": "Final Injector Inlet Pressure [bar]",
    "initial_feed_pressure_drop_bar": "Initial Feed Pressure Drop [bar]",
    "final_feed_pressure_drop_bar": "Final Feed Pressure Drop [bar]",
    "initial_injector_delta_p_bar": "Initial Injector Delta-p [bar]",
    "final_injector_delta_p_bar": "Final Injector Delta-p [bar]",
    "initial_thrust_n": "Initial Thrust [N]",
    "final_thrust_n": "Final Thrust [N]",
    "initial_isp_s": "Initial Isp [s]",
    "final_isp_s": "Final Isp [s]",
    "initial_of_ratio": "Initial O/F [-]",
    "final_of_ratio": "Final O/F [-]",
    "initial_mdot_ox_kg_s": "Initial Oxidizer Flow [kg/s]",
    "final_mdot_ox_kg_s": "Final Oxidizer Flow [kg/s]",
    "initial_mdot_f_kg_s": "Initial Fuel Flow [kg/s]",
    "final_mdot_f_kg_s": "Final Fuel Flow [kg/s]",
    "initial_mdot_total_kg_s": "Initial Total Flow [kg/s]",
    "final_mdot_total_kg_s": "Final Total Flow [kg/s]",
    "initial_oxidizer_flux_kg_m2_s": "Initial Oxidizer Flux [kg/m^2/s]",
    "final_oxidizer_flux_kg_m2_s": "Final Oxidizer Flux [kg/m^2/s]",
    "initial_regression_rate_mm_s": "Initial Regression Rate [mm/s]",
    "final_regression_rate_mm_s": "Final Regression Rate [mm/s]",
    "initial_liquid_density_kg_m3": "Initial Liquid Density [kg/m^3]",
    "final_liquid_density_kg_m3": "Final Liquid Density [kg/m^3]",
    "initial_port_diameter_mm": "Initial Port Diameter [mm]",
    "final_port_diameter_mm": "Final Port Diameter [mm]",
    "initial_tank_quality": "Initial Tank Quality [-]",
    "final_tank_quality": "Final Tank Quality [-]",
}


def variable_label(key):
    return VARIABLE_LABELS.get(key, cea_metric_label(key))
